export const GET_BOOKINGS_REQUEST = 'GET_BOOKINGS_REQUEST';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAIL = 'GET_BOOKINGS_FAIL';
export const GET_BOOKINGS_CLEAR = 'GET_BOOKINGS_CLEAR';

export const CONFIRM_BOOKING_REQUEST = 'CONFIRM_BOOKING_REQUEST';
export const CONFIRM_BOOKING_SUCCESS = 'CONFIRM_BOOKING_SUCCESS';
export const CONFIRM_BOOKING_FAIL = 'CONFIRM_BOOKING_FAIL';
export const CONFIRM_BOOKING_CLEAR = 'CONFIRM_BOOKING_CLEAR';

export const CLIENT_CANCEL_BOOKING_REQUEST = 'CLIENT_CANCEL_BOOKING_REQUEST';
export const CLIENT_CANCEL_BOOKING_SUCCESS = 'CLIENT_CANCEL_BOOKING_SUCCESS';
export const CLIENT_CANCEL_BOOKING_FAIL = 'CLIENT_CANCEL_BOOKING_FAIL';
export const CLIENT_CANCEL_BOOKING_CLEAR = 'CLIENT_CANCEL_BOOKING_CLEAR';

export const ADMIN_CANCEL_BOOKING_REQUEST = 'ADMIN_CANCEL_BOOKING_REQUEST';
export const ADMIN_CANCEL_BOOKING_SUCCESS = 'ADMIN_CANCEL_BOOKING_SUCCESS';
export const ADMIN_CANCEL_BOOKING_FAIL = 'ADMIN_CANCEL_BOOKING_FAIL';
export const ADMIN_CANCEL_BOOKING_CLEAR = 'ADMIN_CANCEL_BOOKING_CLEAR';

export const LIST_BOOKINGS_REQUEST = 'LIST_BOOKINGS_REQUEST';
export const LIST_BOOKINGS_SUCCESS = 'LIST_BOOKINGS_SUCCESS';
export const LIST_BOOKINGS_FAIL = 'LIST_BOOKINGS_FAIL';
export const LIST_BOOKINGS_CLEAR = 'LIST_BOOKINGS_CLEAR';

export const SET_BOOKING_AVAILABILITY_REQUEST =
	'SET_BOOKING_AVAILABILITY_REQUEST';
export const SET_BOOKING_AVAILABILITY_SUCCESS =
	'SET_BOOKING_AVAILABILITY_SUCCESS';
export const SET_BOOKING_AVAILABILITY_FAIL = 'SET_BOOKING_AVAILABILITY_FAIL';
export const SET_BOOKING_AVAILABILITY_CLEAR = 'SET_BOOKING_AVAILABILITY_CLEAR';
