export const GET_BOOKINGS_REQUEST = 'GET_BOOKINGS_REQUEST';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAIL = 'GET_BOOKINGS_FAIL';
export const GET_BOOKINGS_CLEAR = 'GET_BOOKINGS_CLEAR';

export const SUBMIT_BOOKING_REQUEST = 'SUBMIT_BOOKING_REQUEST';
export const SUBMIT_BOOKING_SUCCESS = 'SUBMIT_BOOKING_SUCCESS';
export const SUBMIT_BOOKING_FAIL = 'SUBMIT_BOOKING_FAIL';
export const SUBMIT_BOOKING_CLEAR = 'SUBMIT_BOOKING_CLEAR';

export const VERIFY_CLIENT_REQUEST = 'VERIFY_CLIENT_REQUEST';
export const VERIFY_CLIENT_SUCCESS = 'VERIFY_CLIENT_SUCCESS';
export const VERIFY_CLIENT_FAIL = 'VERIFY_CLIENT_FAIL';
export const VERIFY_CLIENT_CLEAR = 'VERIFY_CLIENT_CLEAR';

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAIL = 'CANCEL_BOOKING_FAIL';
export const CANCEL_BOOKING_CLEAR = 'CANCEL_BOOKING_CLEAR';

export const LIST_BOOKINGS_REQUEST = 'LIST_BOOKINGS_REQUEST';
export const LIST_BOOKINGS_SUCCESS = 'LIST_BOOKINGS_SUCCESS';
export const LIST_BOOKINGS_FAIL = 'LIST_BOOKINGS_FAIL';
export const LIST_BOOKINGS_CLEAR = 'LIST_BOOKINGS_CLEAR';

export const SET_BOOKING_AVAILABILITY_REQUEST =
	'SET_BOOKING_AVAILABILITY_REQUEST';
export const SET_BOOKING_AVAILABILITY_SUCCESS =
	'SET_BOOKING_AVAILABILITY_SUCCESS';
export const SET_BOOKING_AVAILABILITY_FAIL = 'SET_BOOKING_AVAILABILITY_FAIL';
export const SET_BOOKING_AVAILABILITY_CLEAR = 'SET_BOOKING_AVAILABILITY_CLEAR';

export const LIST_CLIENTS_REQUEST = 'LIST_CLIENTS_REQUEST';
export const LIST_CLIENTS_SUCCESS = 'LIST_CLIENTS_SUCCESS';
export const LIST_CLIENTS_FAIL = 'LIST_CLIENTS_FAIL';
export const LIST_CLIENTS_CLEAR = 'LIST_CLIENTS_CLEAR';
