export const GET_BOOKINGS_REQUEST = 'GET_BOOKINGS_REQUEST';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAIL = 'GET_BOOKINGS_FAIL';
export const GET_BOOKINGS_CLEAR = 'GET_BOOKINGS_CLEAR';

export const CONFIRM_BOOKING_REQUEST = 'CONFIRM_BOOKING_REQUEST';
export const CONFIRM_BOOKING_SUCCESS = 'CONFIRM_BOOKING_SUCCESS';
export const CONFIRM_BOOKING_FAIL = 'CONFIRM_BOOKING_FAIL';
export const CONFIRM_BOOKING_CLEAR = 'CONFIRM_BOOKING_CLEAR';

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAIL = 'CANCEL_BOOKING_FAIL';
export const CANCEL_BOOKING_CLEAR = 'CANCEL_BOOKING_CLEAR';
